### ISSUE TITLE
networkwriter :  name 'split' is not defined

### ISSUE THREAD

**Issue by dsmello** [AlexProgramm/pybrain3#1]
On file from pybrain3.tools.xm.networkwriter..NetworkWriter.writeToFile() send a error.

> Traceback (most recent call last):
  File "/home/davi/PycharmProjects/datacompress/testpybrain.py", line 28, in <module>
    networkwriter.NetworkWriter.writeToFile(nn,"test.net")
  File "/home/davi/anaconda3/envs/datascience/lib/python3.5/site-packages/pybrain3/tools/xml/networkwriter.py", line 30, in writeToFile
    w.writeNetwork(net, netroot)
  File "/home/davi/anaconda3/envs/datascience/lib/python3.5/site-packages/pybrain3/tools/xml/networkwriter.py", line 36, in writeNetwork
    netroot.setAttribute('class', canonicClassString(net))
  File "/home/davi/anaconda3/envs/datascience/lib/python3.5/site-packages/pybrain3/utilities.py", line 410, in canonicClassString
    return split(repr(x.__class__), "'")[1]
NameError: name 'split' is not defined

to solve:
line 410 : Change :        `return split(repr(x.__class__), "'")[1]` 
to :           `return str.split(repr(x.__class__), "'")[1]`

**Comment by dsmello** [comment]
i'm made a pull request with the fix

**Comment by Jhonatan-Brandel** [comment]
Same error.

**Comment by jb-dev-github** [comment]
I fixed this error replacing:

<code>return split(repr(x.__class__), "'")[1]  </code>

with:

<code>return repr(x.__class__).split( "'")[1]  </code>

**Comment by AlexProgramm** [comment]
Thank you for fixing. I'm sorry for abandoning this repository.
